

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:  
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=david-6393@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=Dandroid*1
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
     
    
    networks:
      - shared-network
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      # ❌ NO MONTES node_modules desde afuera





  backend-rifas:
    build:
      context: ../backend-rifas-fanny-server-api-rest-main
      dockerfile: Dockerfile
    container_name: backend-rifas
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rifas


    volumes:
      - ../backend-rifas-fanny-server-api-rest-main/uploads:/app/uploads
      
    ports:
      - "3010:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-network  # 👈 CAMBIADO





  agenda:
      image: nginx:alpine
      container_name: agenda
      restart: always
      volumes:
        - ../agenda/dist/agenda/browser:/usr/share/nginx/html:ro
        - ../agenda/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      expose:
        - "80"
      networks:
        - shared-network
networks:
  shared-network:
    driver: bridge  